# Generated by Django 4.2.5 on 2023-10-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education_lifting_delete_blog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lifting',
            options={'ordering': ['name'], 'verbose_name': 'Lifting', 'verbose_name_plural': 'Liftings'},
        ),
        migrations.AlterField(
            model_name='lifting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lifting'),
        ),
    ]
