# Generated by Django 4.2.5 on 2023-10-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_lifting_options_alter_lifting_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiftingGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery_images')),
                ('video', models.FileField(blank=True, null=True, upload_to='gallery_videos')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
    ]
