# Generated by Django 4.2.5 on 2023-10-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_aboutme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liftinggallery',
            name='image',
        ),
        migrations.RemoveField(
            model_name='liftinggallery',
            name='video',
        ),
        migrations.AddField(
            model_name='liftinggallery',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='gallery_files'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='me'),
        ),
    ]
